"""
reporter.py — Formats and prints security alerts generated by detector.py.

This module takes the normalized alert dictionaries and produces a
professional, readable terminal report.  It does not use any external
libraries for formatting (no colorama, rich, etc.) to keep the project
simple and standard-compliant.
"""

def generate_report(alerts):
    """Generate a formatted terminal report from a list of alerts.

    Args:
        alerts: list of alert dictionaries produced by detector functions.

    Returns:
        A single formatted string containing the complete report.
    """
    report_lines = []

    # Header
    report_lines.append("=" * 60)
    report_lines.append("AUTHGUARD - LOG ANALYSIS REPORT")
    report_lines.append("=" * 60)
    report_lines.append("")

    if not alerts:
        report_lines.append("No suspicious activity detected.")
        report_lines.append("All analyzed log entries appear normal.")
        report_lines.append("")
        report_lines.append("=" * 60)
        return "\n".join(report_lines)

    # Summary Statistics
    total_alerts = len(alerts)
    high_count = sum(1 for a in alerts if a.get("severity") == "HIGH")
    medium_count = sum(1 for a in alerts if a.get("severity") == "MEDIUM")
    low_count = sum(1 for a in alerts if a.get("severity") == "LOW")

    report_lines.append("SUMMARY STATISTICS")
    report_lines.append("-" * 20)
    report_lines.append(f"Total Suspicious Events: {total_alerts}")
    report_lines.append(f"  HIGH Severity:   {high_count}")
    report_lines.append(f"  MEDIUM Severity: {medium_count}")
    report_lines.append(f"  LOW Severity:    {low_count}")
    report_lines.append("")
    report_lines.append("=" * 60)
    report_lines.append("DETAILED FINDINGS")
    report_lines.append("=" * 60)
    report_lines.append("")

    # Sort alerts by severity (HIGH first, then MEDIUM, then LOW)
    severity_order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
    sorted_alerts = sorted(
        alerts,
        key=lambda a: severity_order.get(a.get("severity", "LOW"), 99)
    )

    # Detail Section
    for i, alert in enumerate(sorted_alerts, 1):
        severity = alert.get("severity", "UNKNOWN")
        alert_type = alert.get("type", "Unknown Alert")
        
        report_lines.append(f"Event #{i} - [{severity}] {alert_type}")
        report_lines.append("-" * 40)
        
        if "user" in alert and alert["user"]:
            report_lines.append(f"User:       {alert['user']}")
        if "ip" in alert and alert["ip"]:
            report_lines.append(f"IP Address: {alert['ip']}")
            
        if "details" in alert and alert["details"]:
            report_lines.append("Evidence:")
            for k, v in alert["details"].items():
                # Format key from 'snake_case' to 'Title Case' for readability
                formatted_key = k.replace("_", " ").title()
                report_lines.append(f"  - {formatted_key}: {v}")

        report_lines.append("")
        report_lines.append(f"Why Suspicious: {alert.get('explanation', 'No explanation provided.')}")
        report_lines.append(f"Mitigation:     {alert.get('mitigation', 'No mitigation provided.')}")
        report_lines.append("")
        
    report_lines.append("=" * 60)
    report_lines.append("END OF REPORT")
    report_lines.append("=" * 60)

    return "\n".join(report_lines)
